spring.application.name=crud 
# enlace a la DB
spring.datasource.url=jdbc:mysql://localhost:3306/crud
# user y pass de la BD
spring.datasource.username=root
spring.datasource.password=root
# driver para mysql de jbdc
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
# visualizar las consultas
spring.jpa.show-sql:true 
# actualizacion automatica del esquema al ejecutar (al hace un cambio en la tabla hace un alter)
spring.jpa.hibernate.ddl-auto:update